image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

services:
  - mongo

variables:
  MONGO_DATABASE: quotesDB
  MONGO_HOST: mongo

  Host: mongo
  Database: quotesDB

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test_with_lab:
  stage: test
  script: npm test
