image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

services:
  - mongodb

variables:
  MONGO_DATABASE: quotesDB

  Host: mongo
  Database: quotesDB

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test_with_lab:
  stage: test
  script: echo $MONGO_HOST; npm test
  variables:
    MONGO_HOST: mongo
    DATABASE_URL: mongodb
