sudo: required

cache:
  directories:
    - "node_modules"

language: node_js
node_js:
  - "8"
  
services:
  - mongodb
  - docker

before_install:
  - docker build -t johnstratoudakis/quotesdb .
  
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
